export const policySectionEn = {
  title: "PRIVACY POLICY",
  blocks: [
    {
      header: "1. General Provisions",
      text: (
        <>
          By accepting this Privacy Policy (hereinafter – the "Policy"), you acknowledge and agree that your personal data may be collected, processed, and used for the purposes of role-based access management, preparation of statistical, administrative, and other information related to professional training.
          <br /><br />
          Before using the Portal, please carefully review your rights and obligations regarding the processing of personal data, as set forth in Article 8 of the Law of Ukraine "On Personal Data Protection" and this Policy, and confirm your full consent to its terms.
        </>
      ),
    },
    {
      header: "2. Collection and Use of Personal Data",
      text: (
        <>
          Personal data is collected and processed solely on the basis of your explicit, informed, and voluntary decision as the data subject, in order to access and use the functional capabilities of the Portal and in accordance with the purposes set forth herein.
          <br /><br />
          The scope and type of personal data collected and processed may vary depending on the role under which you intend to use the Portal.
          <br /><br />
          By registering on the Portal and completing your personal account details, you may be required to provide, inter alia:
          <ul>
            <li>
              full name, date of birth, gender, or other identifying information, telephone number, and e-mail address;
            </li>
            <li>
              information related to your professional activities, including place of employment, position, job category, specialty, qualifications, academic degree, academic title, etc.;
            </li>
            <li>
              information automatically collected during your use of the Portal, including data submitted via feedback forms and/or electronic communications.
            </li>
          </ul>
        </>
      ),
    },
    {
      header: "3. Purpose of DATA Processing",
      text: (
        <>
          Your personal data may be collected, processed, and used for the following purposes:
          <ul>
            <li>
              to ensure role-based access, including:
              <ul>
                <li>registration of Portal users;</li>
                <li>facilitation of electronic interaction between users via personal accounts;</li>
              </ul>
            </li>
            <li>
              to aggregate and systematize registers and structured data, including:
              <ul>
                <li>creation of user lists;</li>
                <li>monitoring, aggregation, and analysis of statistical data generated by Portal users through their use of the Portal.</li>
              </ul>
            </li>
          </ul>
          <br />
          Personal data shall be retained only for as long as is necessary to fulfill the purposes described herein, or until you terminate your use of the Portal by deleting your personal account.
        </>
      ),
    },
    {
      header: "4. Access to Personal Data",
      text: (
        <>
          Full access to the personal data of registered users is granted exclusively to the duly authorized representative of the Portal Administrator.
        </>
      ),
    },
    {
      header: "5. Disclosure to Third Parties",
      text: (
        <>
          The Portal Administrator (https://www.usfenix.army/) does not sell, lease, or otherwise disclose personal data of registered users to third parties, except as required by applicable law.
          <br /><br />
          Disclosure may occur in cases where third-party service providers are engaged to provide technical support and/or Portal improvement services, subject to contractual confidentiality obligations.
          <br /><br />
          The Portal may contain hyperlinks to third-party websites or online resources. Such third-party resources are governed by their own terms of use and privacy policies. The Portal Administrator does not verify, endorse, or assume responsibility for the accuracy, completeness, legality, or content of such external resources.
        </>
      ),
    },
    {
      header: "6. Data Security",
      text: (
        <>
          The Portal Administrator implements appropriate technical, organizational, and procedural safeguards designed to protect your personal data from loss, unauthorized access, misuse, alteration, or disclosure.
        </>
      ),
    },
    {
      header: "7. Amendments to this Policy",
      text: (
        <>
          The Portal Administrator reserves the right to amend or update this Policy from time to time to reflect changes in data processing practices or legal requirements.
          <br /><br />
          You are encouraged to review this Policy periodically. Any changes will be effective upon publication, with the "last updated" date revised accordingly.
        </>
      ),
    },
    {
      header: "8. Your Rights",
      text: (
        <>
          As a registered user of the Portal, you have the right to:
          <ul>
            <li>obtain information regarding the sources, purpose, and location of your personal data;</li>
            <li>obtain information on the conditions of access to your personal data, including information about third parties to whom such data may be disclosed;</li>
            <li>request, within thirty (30) calendar days (unless otherwise provided by the Law of Ukraine "On Personal Data Protection"), information regarding the processing and use of your personal data;</li>
            <li>object, on legitimate grounds, to the processing of your personal data;</li>
            <li>lodge a complaint regarding the processing of your personal data with the Commissioner of the Verkhovna Rada of Ukraine for Human Rights or with a competent court;</li>
            <li>seek legal remedies in the event of violations of data protection legislation;</li>
            <li>withdraw your consent to the processing of your personal data at any time.</li>
          </ul>
        </>
      ),
    },
    {
      header: "9. Data Controller",
      text: (
        <>
          The owner and controller of personal data is the Main Department of Unmanned Aerial Systems of the State Border Guard Service of Ukraine "Feniks"
        </>
      ),
    },
  ],
};
